server {
  listen 80;
  server_name _;

  # 指定网站根目录
  # Nginx 收到请求后，会默认去这个目录找文件
  # 在你的项目里，这些文件是从前端 dist 拷进去的
  root /usr/share/nginx/html;
  index index.html;

  location / {
    # 先尝试把当前请求当成“文件”来找
    # 如果找不到，再当成“目录”来找
    # 还找不到，就返回 /index.html
    try_files $uri $uri/ /index.html;
  }
  
  # 只要请求路径以 /api/ 开头
  # Nginx 就把请求转发给 http://backend:3000/api/
  location /api/ {
    proxy_pass http://backend:3000/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

# 再多说明几点
# 前端调用 /api/health 接口，实际浏览器都是请求的 baseUrl/api/health，开发环境下是 http://127.0.0.1:5173/api/health，生产环境是 http://121.43.62.173:80/
# 前端这样做的目的是防止跨域问题，例如页面是http://127.0.0.1:5173，接口是http://127.0.0.1:5173/api/health，浏览器会认为是同源
# 在开发环境，vite服务器会将 http://127.0.0.1:5173/api/health 代理到 http://127.0.0.1:3000/api/health
# 在生产环境，nginx服务器会将 http://121.43.62.173:80/api/health 代理到 http://121.43.62.173:80/api/health